# Generated by Django 4.0.3 on 2023-03-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qestion',
            new_name='Question',
        ),
    ]
